#! /bin/sh

install -d -g root -o root -m 0755 -p /etc/qworkerd
install -D -g root -o root -m 0644 -p -t /etc/qworkerd *.templ
install -D -g root -o root -m 0644 -p qworkerd /etc/cfgtool/module.d/qworkerd
